
spring:
  modulith:
    events:
      jdbc-schema-initialization:
        enable: true
  h2:
    console:
      enabled: true
  application:
   name: app-poc
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:next_gen;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    url: jdbc:h2:file:~/h2/db/next_gen1;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8181
