
spring:
  modulith:
    events:
      jdbc-schema-initialization:
        enable: true
  h2:
    console:
      enabled: true
  application:
   name: app-poc
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:next_gen;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
server:
  port: 8181
